# Build Settings
build:
  timeout: 600
  command: make
  dir: .
  legacy: false

lang:
  go:
    path: /usr/lib/go
    root: .
    command:
      build: "make build"
      test:  "make test"
  
  java:
    command: 
      build: "mvn -U clean -Dmaven.test.skip=true package dependency:tree"
      test:  "mvn test"

  nodejs:
    registry: "https://registry.npm.taobao.org/"
    command: 
      build: "npm i"
      test:  "npm test"

  php.command.build: "composer install"

git:
  commit:
    id.length: 6
  ckeckout:
    dir: .
    changelog: true
    credentialsID: jenkins-co

# Web APP
web:
  dir: /data/web

stage:
  dev:    master
  qa:     master
  pre:    master
  git:    master
  build:  master
  docker: master
  k8s:    master

skip:
  build:  false
  test:   false
  docker: false
  k8s:    false
  hpa:    false
  git:    false
  sonar:  false

docker:
  timeout: 300
  registry:
    uri:  
    user: 
    credentialsID: 'Docker-Registry'
  
  image.build.options: 

  file:
    ignore: .dockerignore
    templates:
      - users
      - defaults
      - projects
      - language

k8s:
  run:
    user: 1000
    command:  
  
  affinity:
    provider: "name"
    role: "common"
    region: "cn-shanghai"

  image:
    pullPolicy: "Always"
    pullSecret: "registry-k8s"

  strategy:
    max:
      surge: "10%"
      unavalable: "10%"

  gracePeriodSeconds: 60
  minReadySeconds: 5
  revisionHistoryLimit: 5

  security:
    selinux: false

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"

  probe:
    liveness:
      seconds:
        initialDelay: 60
        timeout: 5
        period: 20

    readiness:
      seconds:
        initialDelay: 60
        timeout: 5
        period: 20